import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/constants/selectAll.ts",
    "src/field-editor/*.ts",
    "src/utils/aiDomScope.ts",
    "src/utils/aiKeyboardScope.ts",
    "src/utils/autocompleteController.ts",
    "src/utils/blockDrag.ts",
    "src/utils/blockSelectionSemantics.ts",
    "src/utils/cellSelection.ts",
    "src/utils/clipboardPayload.ts",
    "src/utils/dataAttributes.ts",
    "src/utils/editorEmptyState.ts",
    "src/utils/editorInteractionModel.ts",
    "src/utils/environment.ts",
    "src/utils/fieldEditor.ts",
    "src/utils/fieldEditorTextEntryAttrs.ts",
    "src/utils/flowCapabilities.ts",
    "src/utils/inlineAtomDragPreview.ts",
    "src/utils/inlineAtomSelection.ts",
    "src/utils/inlineDecorations.ts",
    "src/utils/inlineInputRule.ts",
    "src/utils/listInputRule.ts",
    "src/utils/menuPosition.ts",
    "src/utils/parentIdTree.ts",
    "src/utils/placeholderVisibility.ts",
    "src/utils/pointerSelection.ts",
    "src/utils/replaceElementChildren.ts",
    "src/utils/slashMenuPopupAria.ts",
    "src/utils/suggestionMenuPopupAria.ts",
    "src/utils/selectionFormation.ts",
    "src/utils/selectionPlacement.ts",
    "src/utils/tableDefaults.ts",
    "src/types/paste.ts",
  ],
  format: ["esm", "cjs"],
  dts: { compilerOptions: { stripInternal: true } },
  outDir: "dist",
  clean: true,
  external: ["@input/pen-core", "@input/pen-shortcuts", "@input/pen-types"],
  outExtension({ format }) {
    return { js: format === "esm" ? ".mjs" : ".cjs" };
  },
});
