export {
	AIRoot,
	AITrigger,
	AISelectionTrigger,
	AICommandMenu,
	AICommandInput,
	AICommandList,
	AICommandItem,
	AIGenerationZone,
	AIStructuredTargetPreview,
	AIActionBar,
	AIAcceptButton,
	AIRejectButton,
	AIRetryButton,
	AISuggestion,
	AITrackChanges,
	AIDiffView,
	AIChangeList,
	AIProgress,
	AIToolStream,
	AIContextualPromptTrigger,
	AIContextualPromptSurface,
	AIContextualPromptComposer,
	AIInlineSuggestionControls,
	AIInlineSuggestionFloatingSurface,
	AIInlineSuggestionCount,
	AIInlineSuggestionPreviousButton,
	AIInlineSuggestionNextButton,
	AIInlineSuggestionAcceptButton,
	AIInlineSuggestionRejectButton,
	AIInlineSession,
	AIInlineSessionActions,
	useAIContext,
	type AIRootProps,
	type AITriggerProps,
	type AISelectionTriggerProps,
	type AICommandMenuProps,
	type AICommandInputProps,
	type AICommandListProps,
	type AICommandItemProps,
	type AIGenerationZoneProps,
	type AIStructuredTargetPreviewProps,
	type AIActionBarProps,
	type AIAcceptButtonProps,
	type AIRejectButtonProps,
	type AIRetryButtonProps,
	type AISuggestionProps,
	type AITrackChangesProps,
	type AIDiffViewProps,
	type AIChangeListProps,
	type AIProgressProps,
	type AIToolStreamProps,
	type AIContextualPromptTriggerProps,
	type AIContextualPromptSurfaceProps,
	type AIContextualPromptComposerProps,
	type AIInlineSuggestionControlsProps,
	type AIInlineSuggestionFloatingSurfaceProps,
	type AIInlineSuggestionCountProps,
	type AIInlineSuggestionPreviousButtonProps,
	type AIInlineSuggestionNextButtonProps,
	type AIInlineSuggestionAcceptButtonProps,
	type AIInlineSuggestionRejectButtonProps,
	type AIInlineSessionProps,
	type AIInlineSessionActionsProps,
	type ContextualPromptMode,
	type ContextualPromptPlacement,
	type ContextualPromptSide,
	type UseContextualPromptPlacementOptions,
} from "./primitives/ai/index";
export { useAI } from "./hooks/useAI";
export { useAIDebugLog, type AIDebugLogEntry, type AIDebugLogFastApplyMetrics, type AIDebugLogState } from "./hooks/useAIDebugLog";
export { useAISessions } from "./hooks/useAISessions";
export { useActiveAISession } from "./hooks/useActiveAISession";
export {
	useAIStructuredPreview,
	useActiveAIStructuredPreview,
	useAIStructuredTargetPreview,
	useAIStructuredPreviewContent,
	type AIStructuredPreviewSelection,
	type AIStructuredTargetPreviewSelection,
} from "./hooks/useAIStructuredPreview";
export { useAIActions } from "./hooks/useAIActions";
export { useAISessionActions } from "./hooks/useAISessionActions";
export { useAIStreamEvents } from "./hooks/useAIStreamEvents";
export { useGeneration } from "./hooks/useGeneration";
export { useSuggestions } from "./hooks/useSuggestions";
export {
	useInlineSuggestionControls,
	type InlineSuggestionControlPosition,
	type InlineSuggestionControlsState,
} from "./hooks/useInlineSuggestionControls";
export { useSuggestMode } from "./hooks/useSuggestMode";
export type {
	AIContextualPromptAnchor,
	AIContextualPromptAnchorKind,
	AIContextualPromptAnchorStatus,
	AIContextualPromptComposerState,
	AIContextualPromptRect,
	AIContextualPromptState,
	AIControllerState,
	AISession,
	AISessionFastApplyMetrics,
	AISessionMetrics,
	AISessionPrompt,
	AISessionStatus,
	AISessionTarget,
	AISurface,
	AIStatus,
	AIStreamEvent,
	AIStreamEventType,
	GenerationState,
	GenerationStructuredPreviewState,
	PersistentSuggestion,
	StructuralReviewItem,
	StructuralReviewComparisonRow,
} from "@pen/ai";
