import type { BlockSuggestion as ContractBlockSuggestion } from "@input/pen-types";

export type {
	AIExtensionConfig,
	AIContentFormatOptions,
	AIEditStreaming,
	AISuggestionPresentation,
	ResolvedEditTarget,
	ResolvedEditProposal,
	AIStatus,
	AISurface,
	AISessionStatus,
	AISessionTarget,
	AISessionPrompt,
	AISessionSelectionSnapshot,
	AIContextualPromptRect,
	AIContextualPromptAnchorKind,
	AIContextualPromptAnchorStatus,
	AIContextualPromptAnchor,
	AIContextualPromptComposerState,
	AIContextualPromptState,
	AISessionMetrics,
	AISessionCommitMetrics,
	AISessionAnchor,
	AIStreamingReviewPreviewTarget,
	AIStreamingReviewPreviewInput,
	AIStreamingReviewPreview,
	AISession,
	AIInlineHistorySnapshot,
	AIExternalInlineTurnResult,
	AgenticStep,
	AIStreamEventType,
	AIStreamEvent,
	GenerationState,
	GenerationTargetKind,
	EphemeralSuggestion,
	AIInlineCompletionState,
	AIInlineCompletionController,
	PersistentTextSuggestion,
} from "./types/session";

/** Contract-layer block-suggestion shape; matches runtime actions (RS7). */
export type BlockSuggestion = ContractBlockSuggestion;

export type {
	PersistentBlockSuggestion,
	PersistentSuggestion,
	BlockSuggestionMeta,
	BlockSuggestionPreviousState,
	AIAwarenessState,
	AICommandContext,
	AICommandGuard,
	AICommandBinding,
	AIControllerState,
	AIPromptTarget,
	AISessionResolution,
	AIInlineHistoryDirection,
	AIInlineHistoryController,
	AIReviewController,
	AICommandExecutionOptions,
	AIRequestedOperation,
	AIController,
	AgenticLoopOptions,
	AIWorkingSetEnvelope,
	AIWorkingSetRetrievedSpan,
	StructuredGenerationDebugState,
	CommitDebugState,
	AIMutationReceiptStatus,
	AIMutationReceiptEvidence,
	AIMutationReceipt,
} from "./types/controller";
